routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('careers', App\Http\Controllers\CareerController::class);

Route::get('/careers/{career}/pensum', [App\Http\Controllers\CareerController::class, 'pensum'])->name('career.pensum');

//

Route::resource('sections', App\Http\Controllers\SectionController::class);

Route::get('/sections/{career}/index', [App\Http\Controllers\SectionController::class, 'index'])->name('section.index');

Route::get('/sections/{section}/list', [App\Http\Controllers\SectionController::class, 'list'])->name('section.list');

Route::resource('semesters', App\Http\Controllers\SemesterController::class);

Route::resource('subjects', App\Http\Controllers\SubjectController::class);

Route::resource('notices', App\Http\Controllers\NoticeController::class);

//

Route::resource('users', App\Http\Controllers\UserController::class);

Route::get('/users/view/change', [App\Http\Controllers\UserController::class, 'viewChange'])->name('user.viewChange');

Route::put('/users/view/cambio', [App\Http\Controllers\UserController::class, 'change'])->name('user.cambio');

Route::get('/users/view/{user}/record', [App\Http\Controllers\UserController::class, 'record'])->name('user.record');

Route::get('/constancia/pdf', [App\Http\Controllers\UserController::class, 'pdf'])->name('constancia.pdf');

Route::get('/carnet/pdf', [App\Http\Controllers\UserController::class, 'carnet'])->name('carnet.pdf');


#esta ruta (getSection) es para la funcion de javascript de section
Route::get('getSection',[App\Http\Controllers\UserController::class, 'getSection'])->name('getSection');

Route::get('getSubject',[App\Http\Controllers\UserController::class, 'getSubject'])->name('getSubject');

#rutas de inscripcion con (enrollmenst)
Route::get('/enrollments/create', [App\Http\Controllers\EnrollmentController::class, 'create'])->name('enrollment.create');

Route::post('/enrollments/store', [App\Http\Controllers\EnrollmentController::class, 'store'])->name('enrollment.store');

Route::get('/enrollments/view/{enrollment}/edit', [App\Http\Controllers\EnrollmentController::class, 'edit'])->name('enrollment.edit');

Route::put('/enrollments/view/{enrollment}', [App\Http\Controllers\EnrollmentController::class, 'update'])->name('enrollment.update');

#rutas para asignar a los profesores 

Route::get('/teachers/assigned', [App\Http\Controllers\AssignedTeacherController::class, 'assigned'])->name('teacher.assigned');

Route::post('/teachers/assigned', [App\Http\Controllers\AssignedTeacherController::class, 'store'])->name('teacher.store');

#esta ruta es la segunda fucion del store para la materia que daran los profesores
Route::post('/teachers/{assignedTeacher}', [App\Http\Controllers\AssignedTeacherController::class, 'storeTwo'])->name('teacher.storeTwo');

Route::get('/teachers/view/{user}/historic', [App\Http\Controllers\AssignedTeacherController::class, 'historic'])->name('teacher.historic');

Route::get('/teachers/view/{user}/section', [App\Http\Controllers\AssignedTeacherController::class, 'section'])->name('teacher.section');

Route::get('/teachers/view/{subject}/{section}/getStuden', [App\Http\Controllers\AssignedTeacherController::class, 'getStuden'])->name('teacher.getStuden');

#rutas para los horarios 
Route::get('/schedules/create', [App\Http\Controllers\ScheduleController::class, 'create'])->name('schedule.create');

Route::post('/schedules/create', [App\Http\Controllers\ScheduleController::class, 'store'])->name('schedule.store');

Route::get('/schedules/{career}/{section}', [App\Http\Controllers\ScheduleController::class, 'show'])->name('schedule.show');

app/Models/Career.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Section;
use App\Models\Subject;
use App\Models\User;

class Career extends Model
{
    use HasFactory;

     protected $fillable = ['career_name'];

     public function sections()
     {
        return $this->hasMany(Section::class, 'id');
     }

     public function subjects()
     {
        return $this->hasMany(Subject::class, 'id');
     }

     public function users()
     {
        return $this->hasMany(User::class, 'id');
     }
}

app/Http/Controllers/CareerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Career;
use App\Models\Section;
use App\Models\Subject;
class CareerController extends Controller
{
   
    public function index(Career $career,Request $request)
    {
        $this->authorize('viewAny', $career);

        $subjects = Subject::all();
        $sections = Section::all();
        $careers = Career::orderBy('career_name', 'asc')->paginate(3);

        return view('careers.index', compact('careers', 'sections', 'subjects'));
    }

    public function create(Career $career)
    {
        $this->authorize('create', $career);

        $career = new Career();
        
        return view('careers.create', compact('career'));
    }

    
    public function store(Request $request)
    {
        $career = Career::create($request->all());
        
        return back()->with('status', 'La carrera fue creada exitosamente!');
    }

    public function show($id)
    {
        //
    }

   
    public function edit(Career $career)
    {
        $this->authorize('viewAny', $career);

        #$career = Career::find($id);
        
        return view('careers.edit', compact('career'));
    }

   
    public function update(Request $request, Career $career)
    {
        $career->update($request->all());

        return back()->with('status', 'La carrera fue actualizada exitosamente!');

    }

    public function destroy($id)
    {
        //
    }
    
    public function pensum(Career $career)
    {
        $subjects = Subject::all();

        return view('careers.pensum', compact('subjects','career'));
    }
}

resources/views/careers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-plus"></i> Crear Carrera</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Crear Carrera</li>
                        </ol>
                    </nav>
                     @include('messages')
                    <div class="row">
                        <div class="col-md-5 mb-4">
                            <div class="p-3 border bg-light shadow">
                                <form action="{{ route('careers.store') }}" method="POST">
                                    @csrf
                                    <div class="mb-1">
                                        <label for="career_name" class="form-label">Nombre de la Carrera: </label>
                                        <input type="text" class="form-control" id="career_name" name="career_name" placeholder="Introduzca el nombre de la carrera" required>
                                    </div>
                                    <button type="submit" class="mt-3 btn btn-sm btn-outline-success"><i class="bi bi-check2"></i> Guardar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- @i('layouts.footer') -->
        </div>
    </div>
</div>
@endsection

resources/views/careers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-plus"></i> Editar Carrera</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{url()->previous()}}">Ver Carreras</a></li> 
                            <li class="breadcrumb-item active" aria-current="page">Editar Carrera</li>
                        </ol>
                    </nav>
                    @include('messages')
                    <div class="row">
                        <div class="col-md-5 mb-4">
                            <div class="p-3 border bg-light shadow">
                                <form action="{{ route('careers.update', $career->id) }}" method="POST">
                                @method ('PUT')
                                @csrf
                                    <div class="mb-4">
                                        <label for="career_name" class="form-label">Nombre de la Carrera: </label>
                                        <input type="text" class="form-control" id="career_name" name="career_name" placeholder="Introduzca el nombre de la carrera" value="{{ $career->career_name }}" required>
                                    </div>
                                    <button class="btn btn-sm btn-outline-success" type="submit"><i class="bi bi-check2"></i> Actualizar</button>
                                    <a class="btn btn-sm btn-outline-secondary" href="{{ route ('careers.index') }}"><i class="bi bi-arrow-counterclockwise"></i> Regresar</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- @i('layouts.footer') -->
        </div>
    </div>
</div>
@endsection

resources/views/careers/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-diagram-3"></i> Carreras</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Ver Carreras</li>
                        </ol> 
                    </nav>
                    <div class="row">
                        @foreach ($careers as $career)
                            @php
                                $total_sections = 0;
                            @endphp
                            <div class="col-11">
                                <div class="card my-3 shadow-sm">
                                    <div class="card-header bg-transparent">
                                        
                                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                                            <li class="nav-item" role="presentation">
                                                <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#class{{$career->id}}" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true"><i class="bi bi-diagram-3"></i> {{$career->career_name}}</button>
                                            </li>
                                            <li class="nav-item">
                                               <a style="text-decoration: none;" href="{{route('career.pensum', $career->id)}}"> <button class="nav-link" data-bs-toggle="tab" data-bs-target="#class{{$career->id}}-courses" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false"><i class="bi bi-journal-medical"></i> Pensum</button> </a>
                                            </li>
                                            <li class="nav-item">
                                               <a style="text-decoration: none;" href="{{route('section.index', $career->id)}}"> <button class="nav-link" data-bs-toggle="tab" data-bs-target="#class{{$career->id}}-courses" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false"><i class="bi bi-journal-medical"></i> Secciones</button> </a>
                                            </li>
                                            
                                        </ul>
                                        
                                        <div class="card-body text-dark">
                                            <div class="tab-content" id="myTabContent">
                                                
                                                <div class="tab-pane fade show active" id="class{{$career->id}}" role="tabpanel"> <!-- Carreras -->                                
                                                    <div class="accordion" id="accordionCareer{{$career->id}}">
                                                    @foreach ($sections as $section)
                                                        @if ($section->career_id == $career->id)
                                                            @php
                                                                $total_sections++;
                                                            @endphp

                                                           

                                                        @endif
                                                    @endforeach
                                                    </div>
                                                </div>

                                                
                                            </div>
                                        </div>

                                        <div class="card-footer bg-transparent d-flex justify-content-between">
                                            <span>Secciones: {{$total_sections}}</span>
                                            <span><a href="{{route ('careers.edit', $career->id) }}" class="btn btn-sm btn-outline-success" role="button"><i class="bi bi-pencil"></i> Editar Carrera</a></span>
                                        </div>                                        
                                     
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
            {!! $careers->links('pagination::bootstrap-4') !!}
            <!-- @i('layouts.footer') --> 
        </div>
    </div>
</div>
@endsection

resources/views/careers/pensum.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-person-lines-fill"></i> Pensum de {{$career->career_name}}</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Lista de Materias</li>
                        </ol>
                    </nav>
                    @include('messages')
                    <div class="mb-4 mt-4 col-md-8">
                        <div class="bg-white border shadow-sm p-3 mt-4">
                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">Materia</th>
                                        <th scope="col">Semestre</th>
                                        <th scope="col">Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($subjects as $subject)
                                    @if ($subject->career_id == $career->id)
                                    <tr>
                                        <td>{{$subject->subject_name}}</td>
                                        <td>{{$subject->semesters->semester_name}}</td>
                                        <td>
                                        <a href="{{ route('subjects.edit', $subject->id)}}" role="button" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pen"></i> Editar</a>
                                        </td> 
                                    </tr>
                                    @endif
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!--@i('layouts.footer') -->
        </div>
    </div>
</div>
@endsection