routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('careers', App\Http\Controllers\CareerController::class);

Route::get('/careers/{career}/pensum', [App\Http\Controllers\CareerController::class, 'pensum'])->name('career.pensum');

//

Route::resource('sections', App\Http\Controllers\SectionController::class);

Route::get('/sections/{career}/index', [App\Http\Controllers\SectionController::class, 'index'])->name('section.index');

Route::get('/sections/{section}/list', [App\Http\Controllers\SectionController::class, 'list'])->name('section.list');

Route::resource('semesters', App\Http\Controllers\SemesterController::class);

Route::resource('subjects', App\Http\Controllers\SubjectController::class);

Route::resource('notices', App\Http\Controllers\NoticeController::class);

//

Route::resource('users', App\Http\Controllers\UserController::class);

Route::get('/users/view/change', [App\Http\Controllers\UserController::class, 'viewChange'])->name('user.viewChange');

Route::put('/users/view/cambio', [App\Http\Controllers\UserController::class, 'change'])->name('user.cambio');

Route::get('/users/view/{user}/record', [App\Http\Controllers\UserController::class, 'record'])->name('user.record');

Route::get('/constancia/pdf', [App\Http\Controllers\UserController::class, 'pdf'])->name('constancia.pdf');

Route::get('/carnet/pdf', [App\Http\Controllers\UserController::class, 'carnet'])->name('carnet.pdf');


#esta ruta (getSection) es para la funcion de javascript de section
Route::get('getSection',[App\Http\Controllers\UserController::class, 'getSection'])->name('getSection');

Route::get('getSubject',[App\Http\Controllers\UserController::class, 'getSubject'])->name('getSubject');

#rutas de inscripcion con (enrollmenst)
Route::get('/enrollments/create', [App\Http\Controllers\EnrollmentController::class, 'create'])->name('enrollment.create');

Route::post('/enrollments/store', [App\Http\Controllers\EnrollmentController::class, 'store'])->name('enrollment.store');

Route::get('/enrollments/view/{enrollment}/edit', [App\Http\Controllers\EnrollmentController::class, 'edit'])->name('enrollment.edit');

Route::put('/enrollments/view/{enrollment}', [App\Http\Controllers\EnrollmentController::class, 'update'])->name('enrollment.update');

#rutas para asignar a los profesores 

Route::get('/teachers/assigned', [App\Http\Controllers\AssignedTeacherController::class, 'assigned'])->name('teacher.assigned');

Route::post('/teachers/assigned', [App\Http\Controllers\AssignedTeacherController::class, 'store'])->name('teacher.store');

#esta ruta es la segunda fucion del store para la materia que daran los profesores
Route::post('/teachers/{assignedTeacher}', [App\Http\Controllers\AssignedTeacherController::class, 'storeTwo'])->name('teacher.storeTwo');

Route::get('/teachers/view/{user}/historic', [App\Http\Controllers\AssignedTeacherController::class, 'historic'])->name('teacher.historic');

Route::get('/teachers/view/{user}/section', [App\Http\Controllers\AssignedTeacherController::class, 'section'])->name('teacher.section');

Route::get('/teachers/view/{subject}/{section}/getStuden', [App\Http\Controllers\AssignedTeacherController::class, 'getStuden'])->name('teacher.getStuden');

#rutas para los horarios 
Route::get('/schedules/create', [App\Http\Controllers\ScheduleController::class, 'create'])->name('schedule.create');

Route::post('/schedules/create', [App\Http\Controllers\ScheduleController::class, 'store'])->name('schedule.store');

Route::get('/schedules/{career}/{section}', [App\Http\Controllers\ScheduleController::class, 'show'])->name('schedule.show');

app/Models/Section.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Career;
use App\Models\Semester;
use App\Models\User;

class Section extends Model
{
    use HasFactory;

    protected $fillable = ['section_name', 'career_id','semester_id'];

    public function careers()
    {
        return $this->belongsTo(Career::class, 'career_id');
    }
    public function semesters()
    {
        return $this->belongsTo(Semester::class, 'semester_id');
    }

    public function users()
    {
        return $this->hasMany(User::class, 'id');
    }
    
}

app/Http/Controllers/SectionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Section;
use App\Models\Career;
use App\Models\Semester;
use App\Models\User;
class SectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Career $career)
    {
        $sections = Section::all();

        return view('sections.index',compact('sections','career'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $section = new Section();
        $careers = Career::all();
        $semesters = Semester::all();

        return view('sections.create', compact('section', 'careers','semesters'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $section = Section::create($request->all());
        
        return back()->with('status', 'La sección fue creada exitosamente!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $section = Section::find($id);
        $careers = Career::all();
        $semesters = Semester::all();

        return view('sections.edit', compact('section', 'careers', 'semesters'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Section $section)
    {
        $section->update($request->all());

        return back()->with('status', 'La sección fue actualizada exitosamente!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function list(Section $section)
    {
        $users = User::all();

        return view('sections.list',compact('users', 'section'));
    }
}

resources/views/sections/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-plus"></i> Crear Sección</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Crear Sección</li>
                        </ol>
                    </nav>
                    @include('messages')
                    <div class="row">
                        <div class="col-md-5 mb-4">
                            <div class="p-3 border bg-light shadow">
                                <form action="{{ route('sections.store')}}" method="POST">
                                    @csrf
                                    <div class="mb-4">
                                        <label for="section_name" class="form-label">Nombre de la Sección<sup><i class="bi bi-asterisk text-primary"></i></sup></label>
                                        <input type="text" class="form-control" id="section_name" name="section_name" required>
                                    </div>
                                    <div class="mb-3">
                                        <p>Asignar sección a la carrera:<sup><i class="bi bi-asterisk text-primary"></i></sup></p>
                                        <select class="form-select" name="career_id" aria-label=".form-select" required>
                                            @foreach ($careers as $career)
                                                <option value="{{$career->id}}">{{$career->career_name}}</option>
                                            @endforeach
                                        </select>           
                                    </div>
                                    <div class="mb-3">
                                        <p>Asignar sección al semestre:<sup><i class="bi bi-asterisk text-primary"></i></sup></p>
                                        <select class="form-select" name="semester_id" aria-label=".form-select" required>
                                            @foreach ($semesters as $semester)
                                                <option value="{{$semester->id}}">{{$semester->semester_name}}</option>
                                            @endforeach
                                        </select>           
                                    </div>
                                    <button type="submit" class="mt-3 btn btn-sm btn-outline-success"><i class="bi bi-check2"></i> Guardar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- @i('layouts.footer') -->
        </div>
    </div>
</div>
@endsection

resources/views/sections/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-plus"></i> Editar Sección</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{url()->previous()}}">Ver Carreras</a></li> 
                            <li class="breadcrumb-item active" aria-current="page">Editar Sección</li>
                        </ol>
                    </nav>
                    @include('messages')
                    <div class="row">
                        <div class="col-md-5 mb-4">
                            <div class="p-3 border bg-light shadow">
                                <form action="{{ route('sections.update', $section->id)}}" method="POST">
                                    @method ('PUT')
                                    @csrf
                                    <div class="mb-4">
                                        <label for="section_name" class="form-label">Nombre de la Sección<sup><i class="bi bi-asterisk text-primary"></i></sup></label>
                                        <input type="text" class="form-control" id="section_name" name="section_name" value="{{ $section->section_name }}" required>
                                    </div>
                                    <div class="mb-3">
                                        <p>Asignar sección al semestre:<sup><i class="bi bi-asterisk text-primary"></i></sup></p>
                                        <select class="form-select" name="semester_id" aria-label=".form-select" required>
                                            @foreach ($semesters as $semester)
                                                <option value="{{$semester->id}}">{{$semester->semester_name}}</option>
                                            @endforeach
                                        </select>           
                                    </div>
                                    <button class="btn btn-sm btn-outline-success" type="submit"><i class="bi bi-check2"></i> Actualizar</button>
                                    <a class="btn btn-sm btn-outline-secondary" href="{{ route ('careers.index') }}"><i class="bi bi-arrow-counterclockwise"></i> Regresar</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- @i('layouts.footer') -->
        </div>
    </div>
</div>
@endsection

resources/views/sections/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-person-lines-fill"></i>Secciones de {{$career->career_name}}</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Lista de Secciones</li>
                        </ol>
                    </nav>
                    @include('messages')
                    <div class="mb-4 mt-4 col-md-10">
                        <div class="bg-white border shadow-sm p-3 mt-4">
                            <table class="table table-responsive">
                                <thead>
                                    <tr>
                                        <th scope="col">Nombre</th>
                                        <th scope="col">Semestre</th>
                                        <th scope="col">Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($sections as $section)
                                    @if ($section->career_id == $career->id)
                                    <tr>
                                        <td>{{$section->section_name}}</td>
                                        <td>{{$section->semesters->semester_name}}</td>
                                        
                                        <td>
                                            <div>
                                                <a href="{{ route('section.list', $section->id)}}" role="button" class="btn btn-sm btn-outline-info"><i class="bi bi-eye"> Ver</i></a>
                                                <a href="{{ route('sections.edit', $section->id)}}" role="button" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pen">Editar</i></a>
                                                <a href="{{ route('schedule.show', ['career'=> $career->id,'section'=> $section->id])}}" role="button" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pen"></i> Horario</a>
                                            </div>
                                        </td>
                                    </tr>
                                    @endif
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!--@i('layouts.footer') -->
        </div>
    </div>
</div>
@endsection

resources/views/sections/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-person-lines-fill"></i> Lista de Estudiantes de {{$section->section_name}}</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Lista de Estudiantes</li>
                        </ol>
                    </nav>
                    @include('messages')
                    <div class="mb-4 mt-4">
                        <div class="bg-white border shadow-sm p-3 mt-4">
                            <table class="table table-responsive">
                                <thead>
                                    <tr>
                                        <th scope="col">Nombre</th>
                                        <th scope="col">Apellido</th>
                                        <th scope="col">Correo</th>
                                        <th scope="col">Cédula</th>
                                        <th scope="col">Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($users as $user)
                                    @if ($user->section_id == $section->id)
                                    <tr>
                                        <td>{{$user->first_name}}</td>
                                        <td>{{$user->last_name}}</td>
                                        <td>{{$user->email}}</td>
                                        <td>{{$user->ci}}</td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a href="{{ route('users.show', $user->id)}}" role="button" class="btn btn-sm btn-outline-success"><i class="bi bi-eye"></i> Perfil</a>
                                                <a href="{{ route('users.edit', $user->id)}}" role="button" class="btn btn-sm btn-outline-success"><i class="bi bi-pen"></i> Editar</a>
                                                <a href="{{ route('user.record', $user->id)}}" role="button" class="btn btn-sm btn-outline-success"><i class="bi bi-pen"></i> notas</a>
                                            </div>
                                        </td>
                                    </tr>
                                    @endif
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!--@i('layouts.footer') -->
        </div>
    </div>
</div>
@endsection