routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('careers', App\Http\Controllers\CareerController::class);

Route::get('/careers/{career}/pensum', [App\Http\Controllers\CareerController::class, 'pensum'])->name('career.pensum');

//

Route::resource('sections', App\Http\Controllers\SectionController::class);

Route::get('/sections/{career}/index', [App\Http\Controllers\SectionController::class, 'index'])->name('section.index');

Route::get('/sections/{section}/list', [App\Http\Controllers\SectionController::class, 'list'])->name('section.list');

Route::resource('semesters', App\Http\Controllers\SemesterController::class);

Route::resource('subjects', App\Http\Controllers\SubjectController::class);

Route::resource('notices', App\Http\Controllers\NoticeController::class);

//

Route::resource('users', App\Http\Controllers\UserController::class);

Route::get('/users/view/change', [App\Http\Controllers\UserController::class, 'viewChange'])->name('user.viewChange');

Route::put('/users/view/cambio', [App\Http\Controllers\UserController::class, 'change'])->name('user.cambio');

Route::get('/users/view/{user}/record', [App\Http\Controllers\UserController::class, 'record'])->name('user.record');

Route::get('/constancia/pdf', [App\Http\Controllers\UserController::class, 'pdf'])->name('constancia.pdf');

Route::get('/carnet/pdf', [App\Http\Controllers\UserController::class, 'carnet'])->name('carnet.pdf');


#esta ruta (getSection) es para la funcion de javascript de section
Route::get('getSection',[App\Http\Controllers\UserController::class, 'getSection'])->name('getSection');

Route::get('getSubject',[App\Http\Controllers\UserController::class, 'getSubject'])->name('getSubject');

#rutas de inscripcion con (enrollmenst)
Route::get('/enrollments/create', [App\Http\Controllers\EnrollmentController::class, 'create'])->name('enrollment.create');

Route::post('/enrollments/store', [App\Http\Controllers\EnrollmentController::class, 'store'])->name('enrollment.store');

Route::get('/enrollments/view/{enrollment}/edit', [App\Http\Controllers\EnrollmentController::class, 'edit'])->name('enrollment.edit');

Route::put('/enrollments/view/{enrollment}', [App\Http\Controllers\EnrollmentController::class, 'update'])->name('enrollment.update');

#rutas para asignar a los profesores 

Route::get('/teachers/assigned', [App\Http\Controllers\AssignedTeacherController::class, 'assigned'])->name('teacher.assigned');

Route::post('/teachers/assigned', [App\Http\Controllers\AssignedTeacherController::class, 'store'])->name('teacher.store');

#esta ruta es la segunda fucion del store para la materia que daran los profesores
Route::post('/teachers/{assignedTeacher}', [App\Http\Controllers\AssignedTeacherController::class, 'storeTwo'])->name('teacher.storeTwo');

Route::get('/teachers/view/{user}/historic', [App\Http\Controllers\AssignedTeacherController::class, 'historic'])->name('teacher.historic');

Route::get('/teachers/view/{user}/section', [App\Http\Controllers\AssignedTeacherController::class, 'section'])->name('teacher.section');

Route::get('/teachers/view/{subject}/{section}/getStuden', [App\Http\Controllers\AssignedTeacherController::class, 'getStuden'])->name('teacher.getStuden');

#rutas para los horarios 
Route::get('/schedules/create', [App\Http\Controllers\ScheduleController::class, 'create'])->name('schedule.create');

Route::post('/schedules/create', [App\Http\Controllers\ScheduleController::class, 'store'])->name('schedule.store');

Route::get('/schedules/{career}/{section}', [App\Http\Controllers\ScheduleController::class, 'show'])->name('schedule.show');

app/Models/Semester.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Subject;
use App\Models\Section;

class Semester extends Model
{
    use HasFactory;

    protected $fillable = ['semester_name', 'start_date', 'end_date'];

    public function subjects()
    {
        return $this->hasMany(Subject::class, 'id');
    }
    public function sections()
    {
        return $this->hasMany(Section::class, 'id');
    }

}

app/Http/Controllers/SemesterController.php
<?php

namespace App\Http\Controllers;
use App\Models\Semester;

use Illuminate\Http\Request;

class SemesterController extends Controller
{
    
    public function index()
    {
        $semesters = Semester::all();

        return view ('semesters.index', compact('semesters'));
    }

    
    public function create()
    {
        $semester = new Semester();

        return view('semesters.create', compact('semester'));


    }

    
    public function store(Request $request)
    {
        $semester = Semester::create($request->all());

    
        return back()->with('status', 'El semestre fue creado exitosamente!');

    }

    public function edit($id)
    {
        $semester = Semester::find($id);
        
        return view('semesters.edit', compact('semester'));
    }

   
    public function update(Request $request, Semester $semester)
    {
        $semester->update($request->all());

        return back()->with('status', 'El semestre fue actualizado exitosamente!');
    }
}

resources/views/semesters/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-plus"></i> Crear Semestre</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Crear Semestre</li>
                        </ol>
                    </nav>
                    @include('messages')
                    <div class="row">
                        <div class="col-md-5 mb-4">
                            <div class="p-3 border bg-light shadow">
                                <form action="{{ route('semesters.store')}}" method="POST">
                                        @csrf                                  
                                    <div class="mb-4">
                                        <p>Nombre del Semestre<sup><i class="bi bi-asterisk text-primary"></i></sup></p>
                                        <input type="text" class="form-control" placeholder="Primer Semestre" aria-label="Semester name" name="semester_name" required>
                                    </div>
                                    <button type="submit" class="mt-3 btn btn-sm btn-outline-success"><i class="bi bi-check2"></i> Guardar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- @i('layouts.footer') -->
        </div>
    </div>
</div>
@endsection

resources/views/semesters/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-plus"></i> Editar Semestre</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{url()->previous()}}">Ver Semestres</a></li> 
                            <li class="breadcrumb-item active" aria-current="page">Editar Semestre</li>                                                    
                        </ol>
                    </nav>
                    @include('messages')
                    <div class="row">
                        <div class="col-md-5 mb-4">
                            <div class="p-3 border bg-light shadow">
                                <form action="{{route('semesters.update', $semester->id)}}" method="POST">
                                @method ('PUT')
                                @csrf                                  
                                    <div class="mb-4">
                                        <p>Nombre del Semestre<sup><i class="bi bi-asterisk text-primary"></i></sup></p>
                                        <input type="text" class="form-control" placeholder="Primer Semestre" aria-label="Semester name" name="semester_name" value="{{ $semester->semester_name }}" required>
                                    </div>
                                    <button class="btn btn-sm btn-outline-success" type="submit"><i class="bi bi-check2"></i> Actualizar</button>
                                    <a class="btn btn-sm btn-outline-secondary" href="{{ route ('semesters.index') }}"><i class="bi bi-arrow-counterclockwise"></i> Regresar</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- @i('layouts.footer') -->
        </div>
    </div>
</div>
@endsection

resources/views/semesters/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-start">
        @include('layouts.left-menu')
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-10 col-xxl-10">
            <div class="row pt-2">
                <div class="col ps-4">
                    <h1 class="display-6 mb-3"><i class="bi bi-plus"></i> Semestres Disponibles</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a id="breadcrumb" href="{{route('home')}}">Menú Principal</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Ver Semestre</li>
                        </ol>
                    </nav>
                    <div class="row">
                        <div class="col-md-7 mb-4">
                            <div class="p-3 border bg-light shadow-sm">
                                <table class="table table-striped table-hover">
                                    <thead class="thead">
                                        <tr>
                                            <th>Nombre del Semestre</th>
                                            

                                            <th>Opciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($semesters as $semester)
                                            <tr>
                                                
                                                <td>{{ $semester->semester_name }}</td>
            
                                                <td>
                                                    <a href="{{ route('semesters.edit', $semester->id)}}" class="btn btn-warning btn-sm " title="Modificar">
                                                        Modificar <i class="bi bi-pencil-square"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- @i('layouts.footer') -->
        </div>
    </div>
</div>
@endsection